### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by DiCE1904** [u3mur4/syndicate#2]
[*] Saving config file...
Traceback (most recent call last):
  File "synx.py", line 301, in <module>
    main()
  File "synx.py", line 297, in main
    setup_masternodes()
  File "synx.py", line 258, in setup_masternodes
    setup_first_masternode()
  File "synx.py", line 191, in setup_first_masternode
    f = open('/home/mn1/.Syndicate/Syndicate.conf', 'w')
IOError: [Errno 2] No such file or directory: '/home/mn1/.Syndicate/Syndicate.conf'

**Comment by mikhail5555** [comment]
Please make sure you use Ubuntu 14.04

**Comment by neilkuumar** [comment]
Try to run as root (rather than running script with SUDO)

**Comment by cryptond** [comment]
@DiCE1904 I am getting the same error, any fixes? 

@neilkuumar what do you mean run as root?

**Comment by neilkuumar** [comment]
@cryptond type command "sudo su" first to switch to the root user (root has permissions for all), then run all the other commands

**Comment by cryptond** [comment]
@neilkuumar I logged into my VPS as root, and then input the command "wget https://raw.githubusercontent.com/u3mur4/syndicate/master/synx.py && python synx.py"

I've gotten all the way to entering my rpcuser/password, once i finish that i am prompted to add the priv key but i keep getting the same error after i enter it: 

Traceback (most recent call last):
  File "synx.py", line 301, in <module>
    main()
  File "synx.py", line 297, in main
    setup_masternodes()
  File "synx.py", line 258, in setup_masternodes
    setup_first_masternode()
  File "synx.py", line 191, in setup_first_masternode
    f = open('/home/mn1/.Syndicate/Syndicate.conf', 'w')
IOError: [Errno 2] No such file or directory: '/home/mn1/.Syndicate/Syndicate.conf'

Thanks for you help

**Comment by cryptond** [comment]
@neilkuumar anything?

**Comment by u3mur4** [comment]
4d42b509c639d0a6cacd8ba4126cf65e19f43cf0

**Comment by u3mur4** [comment]
Fixed.
