### ISSUE TITLE
Can't run the synx.py properly now

### ISSUE THREAD

**Issue by filgaia81** [u3mur4/syndicate#5]
I have been using your script to setup 2 masternodes. 1 masternode was working fine.
However, just today, i tried to setup my second masternode. using the same script, it gave me error message like this:

[*] Saving config file...
Traceback (most recent call last):
  File "synx.py", line 301, in <module>
    main()
  File "synx.py", line 297, in main
    setup_masternodes()
  File "synx.py", line 258, in setup_masternodes
    setup_first_masternode()
  File "synx.py", line 191, in setup_first_masternode
    f = open('/home/mn1/.Syndicate/Syndicate.conf', 'w')
IOError: [Errno 2] No such file or directory: '/home/mn1/.Syndicate/Syndicate.conf'

Apparently when i checked, the Syndicate wallet wasn't created at all either. That's why it can't find the file.

Is there something buggy in your newest script? Kindly advise.

Thanks

**Comment by pup-tv** [comment]
Syndicate just updated the src, and there isn't a makefile.unix any more.

I needed to:
./autogen.sh
chmod +x ./contrib/install_db4.sh `pwd`
./contrib/install_db4.sh `pwd`
export BDB_PREFIX='/opt/SyndicateQT/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make

To get the program to compile.

But I was using a different vps...  

Others may work with just: 

./autogen.sh
./configure
make

if they have a working version of Berkley DB 4.8.

Good luck!

**Comment by u3mur4** [comment]
The IOError is fixed #2.

**Comment by u3mur4** [comment]
Updated the script. It should work now.
